### ISSUE TITLE
 Use @mixin for aliasing @for loops

### ISSUE THREAD

**Issue by shinsouhitoshi1203** [shinsouhitoshi1203/sass-grid-system#2]
**Description**: Too many `@for` loops. Example belows:
```scss
@for $i from 1 through 12 {
    .col#{$include-bp}-#{$i} {
        flex: 0 0 auto;
        width: calc(100% / #{$grid-column-base} * #{$i});
    }
}

@for $i from 0 through 11 {
    .offset#{$include-bp}-#{$i} {
        margin-left: calc(100% / #{$grid-column-base} * #{$i});
    }
}
```

**Suggestion**: use `@mixin` for aliasing `@for` loops
